export const listActionType = {
    CREATE_REQUEST: 'LIST_CREATE_REQUEST',
    CREATE_SUCCESS: 'LIST_CREATE_SUCCESS',
    CREATE_FAILURE: 'LIST_CREATE_FAILURE',

    REMOVE_REQUEST: 'LIST_REMOVE_REQUEST',
    REMOVE_SUCCESS: 'LIST_REMOVE_SUCCESS',
    REMOVE_FAILURE: 'LIST_REMOVE_FAILURE',

    UPDATE_REQUEST: 'LIST_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'LIST_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'LIST_UPDATE_FAILURE',

    GETALL_REQUEST: 'LIST_GETALL_REQUEST',
    GETALL_SUCCESS: 'LIST_GETALL_SUCCESS',
    GETALL_FAILURE: 'LIST_GETALL_FAILURE',

    GETBYUSER_REQUEST: 'LIST_GETBYUSER_REQUEST',
    GETBYUSER_SUCCESS: 'LIST_GETBYUSER_SUCCESS',
    GETBYUSER_FAILURE: 'LIST_GETBYUSER_FAILURE',

    GETBYID_REQUEST: 'LIST_GETBYID_REQUEST',
    GETBYID_SUCCESS: 'LIST_GETBYID_SUCCESS',
    GETBYID_FAILURE: 'LIST_GETBYID_FAILURE',
}