export const taskActionType = {
    CREATE_REQUEST: 'TASK_CREATE_REQUEST',
    CREATE_SUCCESS: 'TASK_CREATE_SUCCESS',
    CREATE_FAILURE: 'TASK_CREATE_FAILURE',

    UPDATE_REQUEST: 'TASK_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'TASK_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'TASK_UPDATE_FAILURE',

    REMOVE_REQUEST: 'TASK_REMOVE_REQUEST',
    REMOVE_SUCCESS: 'TASK_REMOVE_SUCCESS',
    REMOVE_FAILURE: 'TASK_REMOVE_FAILURE',

    GETBYLIST_REQUEST: 'TASK_GETBYLIST_REQUEST',
    GETBYLIST_SUCCESS: 'TASK_GETBYLIST_SUCCESS',
    GETBYLIST_FAILURE: 'TASK_GETBYLIST_FAILURE',

};